# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel

	platform :ios, '8.0'
	pod 'SDWebImage', '~> 5.0'
	pod 'AFNetworking'

end
